spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

  data:
    redis:
      port: 6379
      host: localhost

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线的自动转换
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#    #目的是为了省略resultType里的代码量
#    type-aliases-package: com.wzf.pojo
server:
  port: 9998

xxlJob:
  accessToken: default_token
  adminAddress: http://localhost:8888/xxl-job-admin
  executor:
    appname: testJob
    ip:
    port: 9997
    logpath: logs/xxlJob
    logretentiondays: 5